---
- name: install gnome core packages
  pacman:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - "{{ gnome_core_packages }}"
  tags: gnome

- name: install gnome extra packages
  pacman:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - "{{ gnome_extra_packages }}"
  tags: gnome

- name: enable gdm login manager
  service:
    name: gdm
    enabled: true
