---
- name: install gnome base packages
  pacman:
    name: "{{ item }}"
    update_cache: true
  with_items: "{{ gnome.packages }}"
  tags: gnome

- name: enable gdm login manager
  service:
    name: gdm
    enabled: true
