---
- name: install gnome base packages
  pacman:
    name: "{{ gnome.packages }}"
    update_cache: true
  tags: gnome

- name: enable gdm login manager
  service:
    name: gdm
    enabled: true
  tags: gnome
